version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
         name: Build Docker image
         command: docker build -t hyperbotauthor/lc0 .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
