version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
         name: Build Docker image
         command: docker build -t hyperbotauthor/herokudocker:$CIRCLE_SHA1 .
      
      - run:
          name: Push to DockerHub
          command: |
            docker login -u hyperbotauthor -p $DOCKERHUB_PASSWORD
            docker push hyperbotauthor/herokudocker:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
